### ISSUE TITLE
[BUGFIX] JQuery UI Fehler fixen

### ISSUE THREAD

**Issue by thomasrehm** [thomasrehm/wbt-fotografie#2]
Fehler tritt bei reload mit Hash in URL auf

**Comment by sasschreiber** [comment]
@thomasrehm Bei mir tritt der Fehler nach der Umstellung auf $(window).load nicht mehr auf. Bei dir?

**Comment by thomasrehm** [comment]
Bei mir auch nicht. Ich schließe diesen Issue
