### ISSUE TITLE
[TASK] Hinweis falls Internetverbindung nicht verfügbar

### ISSUE THREAD

**Issue by thomasrehm** [thomasrehm/wbt-fotografie#7]
Sollte eine Internetverbindung notwendig sein, weisen Sie den Nutzer bei fehlender Internetverbindung mittels Dialog darauf hin.

**Comment by sasschreiber** [comment]
Fixed with abf7454e42297d5ebb698ff411014fe638ddc193

**Comment by sasschreiber** [comment]
(Alert ist auskommentiert. Ich finde es im Inhalt präsent genug...)
